### ISSUE TITLE
How to set actor order on diagram?

### ISSUE THREAD

**Issue by vit1251** [kjagiello/diagwiz#10]
How to make prio for actor on diagram? Have some idea or keyword for set order on screen?

**Comment by kjagiello** [comment]
The only way to do that right now is to utilize `alias`. Diagwiz will order the actors according to the order of aliases.

```
alias a = "Alice"
alias b = "Bob"

a->b: "Hello!"
b->a: "Hello back!"
```
[See in playground](https://diagwiz.io/playground/?input=IYGwlsDOAEzQvNARAQXAYwKZIFCgjAEYLIBCA9obngLQB8hAXMgBKYgjkCEuh9wzJGw7lohYOgDWPIA)

vs
```
alias b = "Bob"
alias a = "Alice"

a->b: "Hello!"
b->a: "Hello back!"
```
[See in playground](https://diagwiz.io/playground/?input=IYGwlsDOAEBG0F5oCIBCB7WyBQoI2ERQEFwBjAUx1wFoA+WALhQAkKQR0BCHWe4ZsjYd0cYGQDWPIA)

Le me know if I misunderstood your question.

**Comment by vit1251** [comment]
That's working. Thanks.
